### ISSUE TITLE
Pedido de Remoção

### ISSUE THREAD

**Issue by takedownsantana** [SandroGRPQA/PlaybookFR#2]
Prezado Sr. Sandro Lopes,

A Apura Cyber Security S.A. foi contratada pelo QUINTO ANDAR para remover conteúdo que contenha propriedade intelectual da empresa ou represente algum risco à sua segurança da informação ou que violem os termos de uso de seus serviços.

Considerando que este projeto exp`e informações sensíveis e utiliza indevidamente a marca registrada de nosso cliente, solicitamos, cordialmente, que remova as seguintes páginas:

https://github.com/SandroGRPQA/PlaybookFR

Deste modo, solicito, cordialmente, que remova estas páginas.

Certo de que seremos atendidos neste cordial pedido, me despeço com votos de elevada estima.

Julius Santana
Advogado - OABSP 308.238
Apura Cybersecurity.

**Comment by SandroGRPQA** [comment]
Removido
